finish separation of tl_scripts and linked_scripts
git-svn-id: svn://tug.org/texlive/trunk/Build/source@28928 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/texk/chktex/Makefile.in b/texk/chktex/Makefile.in
--- a/texk/chktex/Makefile.in
+++ b/texk/chktex/Makefile.in
@@ -534,7 +534,7 @@ top_srcdir = @top_srcdir@
 #************************************************************************
 ACLOCAL_AMFLAGS = -I ../../m4
 EXTRA_DIST = $(CHKTEX_TREE) $(CHKTEX_TREE)-PATCHES regex/COPYING.LIB \
-	regex/README ../../build-aux/relpath $(TESTS)
+	regex/README $(top_builddir)/../../build-aux/relpath $(TESTS)
 AM_CPPFLAGS = $(REGEX_INCLUDES) $(KPATHSEA_INCLUDES) -DKPATHSEA
 AM_CFLAGS = $(WARNING_CFLAGS)
 chktex_SOURCES = $(CHKTEX_TREE)/ChkTeX.c $(CHKTEX_TREE)/ChkTeX.h \
@@ -1601,9 +1601,14 @@ install-sh-links:
 
 # We support native builds, multiplatform or not, as well as distro builds.
 install-links:
-	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
+	@relpath="$(top_srcdir)/../../build-aux/relpath"; \
+	test -r $$relpath || { \
+	  echo 'script_links.am:install-links: could not find relpath script'; \
+	  exit 1; \
+	}; \
+	REL=`$(SHELL) $$relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
 	if test -z "$$REL"; then \
-	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+	  echo 'script_links.am:install_links: unable to compute relative path for linked $(TYPE) scripts' >&2; \
 	  exit 1; \
 	fi; \
 	cd $(DESTDIR)$(bindir) && \
diff --git a/texk/tex4htk/Makefile.in b/texk/tex4htk/Makefile.in
--- a/texk/tex4htk/Makefile.in
+++ b/texk/tex4htk/Makefile.in
@@ -335,23 +335,23 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 ACLOCAL_AMFLAGS = -I ../../m4
-EXTRA_DIST = java ../../build-aux/relpath dbcontext dblatex dbmcontext \
-	dbmex dbmlatex dbmmex dbmtex dbmtexi dbmxelatex dbmxetex dbtex \
-	dbtexi dbxelatex dbxetex demo.tex escontext eslatex esmex \
-	estex estexi esxelatex esxetex jh1context jh1latex jh1mex \
-	jh1tex jh1texi jh1xelatex jh1xetex jhcontext jhlatex jhmex \
-	jhtex jhtexi jhxelatex jhxetex jmcontext jmlatex jmmex jmtex \
-	jmtexi jmxelatex jmxetex jscontext jslatex jsmex jstex jstexi \
-	jsxelatex jsxetex mzcontext mzlatex mzmex mztex mztexi \
-	mzxelatex mzxetex oocontext oolatex oomex ootex ootexi \
-	ooxelatex ooxetex teicontext teilatex teimcontext teimex \
-	teimlatex teimmex teimtex teimtexi teimxelatex teimxetex \
-	teitex teitexi teixelatex teixetex test.tex test1.tex \
-	testa.tex testb.tex uxhcontext uxhlatex uxhmex uxhtex uxhtexi \
-	uxhxelatex uxhxetex wcontext wlatex wmex wtex wtexi wxelatex \
-	wxetex xhcontext xhlatex xhmcontext xhmex xhmlatex xhmmex \
-	xhmtex xhmtexi xhmxelatex xhmxetex xhtex xhtexi xhxelatex \
-	xhxetex xv4ht.java
+EXTRA_DIST = java $(top_builddir)/../../build-aux/relpath dbcontext \
+	dblatex dbmcontext dbmex dbmlatex dbmmex dbmtex dbmtexi \
+	dbmxelatex dbmxetex dbtex dbtexi dbxelatex dbxetex demo.tex \
+	escontext eslatex esmex estex estexi esxelatex esxetex \
+	jh1context jh1latex jh1mex jh1tex jh1texi jh1xelatex jh1xetex \
+	jhcontext jhlatex jhmex jhtex jhtexi jhxelatex jhxetex \
+	jmcontext jmlatex jmmex jmtex jmtexi jmxelatex jmxetex \
+	jscontext jslatex jsmex jstex jstexi jsxelatex jsxetex \
+	mzcontext mzlatex mzmex mztex mztexi mzxelatex mzxetex \
+	oocontext oolatex oomex ootex ootexi ooxelatex ooxetex \
+	teicontext teilatex teimcontext teimex teimlatex teimmex \
+	teimtex teimtexi teimxelatex teimxetex teitex teitexi \
+	teixelatex teixetex test.tex test1.tex testa.tex testb.tex \
+	uxhcontext uxhlatex uxhmex uxhtex uxhtexi uxhxelatex uxhxetex \
+	wcontext wlatex wmex wtex wtexi wxelatex wxetex xhcontext \
+	xhlatex xhmcontext xhmex xhmlatex xhmmex xhmtex xhmtexi \
+	xhmxelatex xhmxetex xhtex xhtexi xhxelatex xhxetex xv4ht.java
 AM_CPPFLAGS = $(KPATHSEA_INCLUDES) -DANSI -DKPATHSEA
 AM_CFLAGS = $(WARNING_CFLAGS)
 t4ht_SOURCES = t4ht.c
@@ -1007,9 +1007,14 @@ install-sh-links:
 
 # We support native builds, multiplatform or not, as well as distro builds.
 install-links:
-	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
+	@relpath="$(top_srcdir)/../../build-aux/relpath"; \
+	test -r $$relpath || { \
+	  echo 'script_links.am:install-links: could not find relpath script'; \
+	  exit 1; \
+	}; \
+	REL=`$(SHELL) $$relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
 	if test -z "$$REL"; then \
-	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+	  echo 'script_links.am:install_links: unable to compute relative path for linked $(TYPE) scripts' >&2; \
 	  exit 1; \
 	fi; \
 	cd $(DESTDIR)$(bindir) && \
diff --git a/utils/ps2eps/Makefile.in b/utils/ps2eps/Makefile.in
--- a/utils/ps2eps/Makefile.in
+++ b/utils/ps2eps/Makefile.in
@@ -453,7 +453,8 @@ top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 ACLOCAL_AMFLAGS = -I ../../m4
 EXTRA_DIST = $(PS2EPS_TREE) $(PS2EPS_TREE)-PATCHES \
-	../../build-aux/relpath $(TESTS) tests/plot.pbm tests/plot.out
+	$(top_builddir)/../../build-aux/relpath $(TESTS) \
+	tests/plot.pbm tests/plot.out
 AM_CFLAGS = $(WARNING_CFLAGS)
 bbox_SOURCES = \
 	$(PS2EPS_TREE)/src/C/bbox.c
@@ -1245,9 +1246,14 @@ install-sh-links:
 
 # We support native builds, multiplatform or not, as well as distro builds.
 install-links:
-	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
+	@relpath="$(top_srcdir)/../../build-aux/relpath"; \
+	test -r $$relpath || { \
+	  echo 'script_links.am:install-links: could not find relpath script'; \
+	  exit 1; \
+	}; \
+	REL=`$(SHELL) $$relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
 	if test -z "$$REL"; then \
-	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+	  echo 'script_links.am:install_links: unable to compute relative path for linked $(TYPE) scripts' >&2; \
 	  exit 1; \
 	fi; \
 	cd $(DESTDIR)$(bindir) && \
diff --git a/utils/psutils/Makefile.in b/utils/psutils/Makefile.in
--- a/utils/psutils/Makefile.in
+++ b/utils/psutils/Makefile.in
@@ -479,7 +479,7 @@ top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 ACLOCAL_AMFLAGS = -I ../../m4
 EXTRA_DIST = $(PSUTILS_TREE) $(PSUTILS_TREE)-PATCHES \
-	../../build-aux/relpath $(TESTS) tests/play.ps \
+	$(top_builddir)/../../build-aux/relpath $(TESTS) tests/play.ps \
 	tests/playbook.2 tests/playnup.2 tests/playps.2 \
 	tests/playres.ps tests/playsel.2 tests/plot.eps \
 	tests/ploth.eps tests/plotm.eps tests/plotv.eps
@@ -1523,9 +1523,14 @@ install-sh-links:
 
 # We support native builds, multiplatform or not, as well as distro builds.
 install-links:
-	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
+	@relpath="$(top_srcdir)/../../build-aux/relpath"; \
+	test -r $$relpath || { \
+	  echo 'script_links.am:install-links: could not find relpath script'; \
+	  exit 1; \
+	}; \
+	REL=`$(SHELL) $$relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
 	if test -z "$$REL"; then \
-	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+	  echo 'script_links.am:install_links: unable to compute relative path for linked $(TYPE) scripts' >&2; \
 	  exit 1; \
 	fi; \
 	cd $(DESTDIR)$(bindir) && \
diff --git a/utils/texdoctk/Makefile.in b/utils/texdoctk/Makefile.in
--- a/utils/texdoctk/Makefile.in
+++ b/utils/texdoctk/Makefile.in
@@ -230,7 +230,7 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 ACLOCAL_AMFLAGS = -I ../../m4
-EXTRA_DIST = ../../build-aux/relpath
+EXTRA_DIST = $(top_builddir)/../../build-aux/relpath
 perl_scripts = texdoctk
 scriptsdir = texmf/scripts/texdoctk
 nodist_bin_SCRIPTS = $(am__append_1)
@@ -705,9 +705,14 @@ install-sh-links:
 
 # We support native builds, multiplatform or not, as well as distro builds.
 install-links:
-	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
+	@relpath="$(top_srcdir)/../../build-aux/relpath"; \
+	test -r $$relpath || { \
+	  echo 'script_links.am:install-links: could not find relpath script'; \
+	  exit 1; \
+	}; \
+	REL=`$(SHELL) $$relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
 	if test -z "$$REL"; then \
-	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+	  echo 'script_links.am:install_links: unable to compute relative path for linked $(TYPE) scripts' >&2; \
 	  exit 1; \
 	fi; \
 	cd $(DESTDIR)$(bindir) && \
diff --git a/utils/xindy/Makefile.in b/utils/xindy/Makefile.in
--- a/utils/xindy/Makefile.in
+++ b/utils/xindy/Makefile.in
@@ -318,7 +318,7 @@ EXTRA_DIST = README-clisp $(XINDY_TREE)-PATCHES $(XINDY_TREE)/AUTHORS \
 	$(XINDY_TREE)/make-rules/alphabets/Makefile.am.not-yet \
 	$(XINDY_TREE)/make-rules/alphabets/lang.defs \
 	$(XINDY_TREE)/make-rules/alphabets/mk-lang.sh \
-	../../build-aux/relpath
+	$(top_builddir)/../../build-aux/relpath
 SUBDIRS = . $(XINDY_TREE)
 DIST_SUBDIRS = $(SUBDIRS)
 DISTCLEANFILES = config.force
@@ -894,9 +894,14 @@ install-sh-links:
 
 # We support native builds, multiplatform or not, as well as distro builds.
 install-links:
-	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
+	@relpath="$(top_srcdir)/../../build-aux/relpath"; \
+	test -r $$relpath || { \
+	  echo 'script_links.am:install-links: could not find relpath script'; \
+	  exit 1; \
+	}; \
+	REL=`$(SHELL) $$relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
 	if test -z "$$REL"; then \
-	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+	  echo 'script_links.am:install_links: unable to compute relative path for linked $(TYPE) scripts' >&2; \
 	  exit 1; \
 	fi; \
 	cd $(DESTDIR)$(bindir) && \
