update tests for 'make check'
git-svn-id: svn://tug.org/texlive/trunk/Build/source@13153 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/texk/dvipsk/Makefile.in b/texk/dvipsk/Makefile.in
--- a/texk/dvipsk/Makefile.in
+++ b/texk/dvipsk/Makefile.in
@@ -179,6 +179,7 @@ INSTALL_STRIP_PROGRAM = @INSTALL_STRIP_PROGRAM@
 KPATHSEA_DEPEND = @KPATHSEA_DEPEND@
 KPATHSEA_INCLUDES = @KPATHSEA_INCLUDES@
 KPATHSEA_LIBS = @KPATHSEA_LIBS@
+KPSEWHICH = @KPSEWHICH@
 LD = @LD@
 LDFLAGS = @LDFLAGS@
 LIBOBJS = @LIBOBJS@
@@ -327,15 +328,19 @@ dist_prologues = \
 prologdir = ${prefix}/texmf/dvips/base
 prologues = $(dist_prologues:.lpro=.pro) texc.pro
 SUFFIXES = .pro .lpro
-EXTRA_DIST = $(dist_prologues) texc.script INSTALLATION atari \
-	cmfonts.map config.ps contrib/PSTricks contrib/afm-extra \
-	contrib/colorsep.lpro contrib/configs contrib/crop.lpr \
-	contrib/latex209 contrib/volker contrib/whichinpath \
-	cyrfonts.map eufonts.map flib.c hps lafonts.map makefont.c \
-	mtest.ps mvs pc psfonts.map reencode test.ps testdata tex \
+EXTRA_DIST = $(dist_prologues) texc.script dvips.test \
+	testdata/dvipstst.tex testdata/dvipstst.xdv \
+	testdata/dvipstst.xps INSTALLATION atari cmfonts.map config.ps \
+	contrib/PSTricks contrib/afm-extra contrib/colorsep.lpro \
+	contrib/configs contrib/crop.lpr contrib/latex209 \
+	contrib/volker contrib/whichinpath cyrfonts.map eufonts.map \
+	flib.c hps lafonts.map makefont.c mtest.ps mvs pc psfonts.map \
+	reencode test.ps testdata/pfbincl.eps testdata/pfbincl.tex tex \
 	vmcms vms Makefile.in.orig configure.in.orig depend.make \
 	depend.mk
-CLEANFILES = $(prologues) texc.lpro
+CLEANFILES = $(prologues) texc.lpro missfont.log mtest.ps dvipstst.ps
+TESTS = dvips.test
+TESTS_ENVIRONMENT = KPSEWHICH='$(KPSEWHICH)'
 all: c-auto.h
 	$(MAKE) $(AM_MAKEFLAGS) all-recursive
 
@@ -813,6 +818,92 @@ GTAGS:
 distclean-tags:
 	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
 
+check-TESTS: $(TESTS)
+	@failed=0; all=0; xfail=0; xpass=0; skip=0; \
+	srcdir=$(srcdir); export srcdir; \
+	list=' $(TESTS) '; \
+	if test -n "$$list"; then \
+	  for tst in $$list; do \
+	    if test -f ./$$tst; then dir=./; \
+	    elif test -f $$tst; then dir=; \
+	    else dir="$(srcdir)/"; fi; \
+	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *[\ \	]$$tst[\ \	]*) \
+		xpass=`expr $$xpass + 1`; \
+		failed=`expr $$failed + 1`; \
+		echo "XPASS: $$tst"; \
+	      ;; \
+	      *) \
+		echo "PASS: $$tst"; \
+	      ;; \
+	      esac; \
+	    elif test $$? -ne 77; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *[\ \	]$$tst[\ \	]*) \
+		xfail=`expr $$xfail + 1`; \
+		echo "XFAIL: $$tst"; \
+	      ;; \
+	      *) \
+		failed=`expr $$failed + 1`; \
+		echo "FAIL: $$tst"; \
+	      ;; \
+	      esac; \
+	    else \
+	      skip=`expr $$skip + 1`; \
+	      echo "SKIP: $$tst"; \
+	    fi; \
+	  done; \
+	  if test "$$all" -eq 1; then \
+	    tests="test"; \
+	    All=""; \
+	  else \
+	    tests="tests"; \
+	    All="All "; \
+	  fi; \
+	  if test "$$failed" -eq 0; then \
+	    if test "$$xfail" -eq 0; then \
+	      banner="$$All$$all $$tests passed"; \
+	    else \
+	      if test "$$xfail" -eq 1; then failures=failure; else failures=failures; fi; \
+	      banner="$$All$$all $$tests behaved as expected ($$xfail expected $$failures)"; \
+	    fi; \
+	  else \
+	    if test "$$xpass" -eq 0; then \
+	      banner="$$failed of $$all $$tests failed"; \
+	    else \
+	      if test "$$xpass" -eq 1; then passes=pass; else passes=passes; fi; \
+	      banner="$$failed of $$all $$tests did not behave as expected ($$xpass unexpected $$passes)"; \
+	    fi; \
+	  fi; \
+	  dashes="$$banner"; \
+	  skipped=""; \
+	  if test "$$skip" -ne 0; then \
+	    if test "$$skip" -eq 1; then \
+	      skipped="($$skip test was not run)"; \
+	    else \
+	      skipped="($$skip tests were not run)"; \
+	    fi; \
+	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$skipped"; \
+	  fi; \
+	  report=""; \
+	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
+	    report="Please report to $(PACKAGE_BUGREPORT)"; \
+	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$report"; \
+	  fi; \
+	  dashes=`echo "$$dashes" | sed s/./=/g`; \
+	  echo "$$dashes"; \
+	  echo "$$banner"; \
+	  test -z "$$skipped" || echo "$$skipped"; \
+	  test -z "$$report" || echo "$$report"; \
+	  echo "$$dashes"; \
+	  test "$$failed" -eq 0; \
+	else :; fi
+
 distdir: $(DISTFILES)
 	$(am__remove_distdir)
 	test -d $(distdir) || mkdir $(distdir)
@@ -965,6 +1056,7 @@ distcleancheck: distclean
 	       $(distcleancheck_listfiles) ; \
 	       exit 1; } >&2
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-recursive
 all-am: Makefile $(INFO_DEPS) $(PROGRAMS) $(MANS) $(DATA) c-auto.h
 installdirs: installdirs-recursive
@@ -1022,8 +1114,6 @@ info: info-recursive
 info-am: $(INFO_DEPS)
 
 install-data-am: install-info-am install-man install-prologDATA
-	@$(NORMAL_INSTALL)
-	$(MAKE) $(AM_MAKEFLAGS) install-data-hook
 
 install-dvi: install-dvi-recursive
 
@@ -1037,8 +1127,6 @@ install-dvi-am: $(DVIS)
 	  $(INSTALL_DATA) "$$d$$p" "$(DESTDIR)$(dvidir)/$$f"; \
 	done
 install-exec-am: install-binPROGRAMS
-	@$(NORMAL_INSTALL)
-	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
 
 install-html: install-html-recursive
 
@@ -1140,36 +1228,33 @@ ps-am: $(PSS)
 uninstall-am: uninstall-binPROGRAMS uninstall-dvi-am uninstall-html-am \
 	uninstall-info-am uninstall-man uninstall-pdf-am \
 	uninstall-prologDATA uninstall-ps-am
-	@$(NORMAL_INSTALL)
-	$(MAKE) $(AM_MAKEFLAGS) uninstall-hook
 
 uninstall-man: uninstall-man1
 
 .MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) install-am \
-	install-data-am install-exec-am install-strip uninstall-am
+	install-strip
 
 .PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
-	all all-am am--refresh check check-am clean clean-binPROGRAMS \
-	clean-generic clean-libtool ctags ctags-recursive dist \
-	dist-all dist-bzip2 dist-gzip dist-hook dist-info dist-lzma \
-	dist-shar dist-tarZ dist-zip distcheck distclean \
-	distclean-compile distclean-generic distclean-hdr \
+	all all-am am--refresh check check-TESTS check-am clean \
+	clean-binPROGRAMS clean-generic clean-libtool ctags \
+	ctags-recursive dist dist-all dist-bzip2 dist-gzip dist-hook \
+	dist-info dist-lzma dist-shar dist-tarZ dist-zip distcheck \
+	distclean distclean-compile distclean-generic distclean-hdr \
 	distclean-libtool distclean-tags distcleancheck distdir \
 	distuninstallcheck dvi dvi-am html html-am info info-am \
 	install install-am install-binPROGRAMS install-data \
-	install-data-am install-data-hook install-dvi install-dvi-am \
-	install-exec install-exec-am install-exec-hook install-html \
-	install-html-am install-info install-info-am install-man \
-	install-man1 install-pdf install-pdf-am install-prologDATA \
-	install-ps install-ps-am install-strip installcheck \
-	installcheck-am installdirs installdirs-am maintainer-clean \
-	maintainer-clean-aminfo maintainer-clean-generic mostlyclean \
-	mostlyclean-aminfo mostlyclean-compile mostlyclean-generic \
-	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-recursive \
-	uninstall uninstall-am uninstall-binPROGRAMS uninstall-dvi-am \
-	uninstall-hook uninstall-html-am uninstall-info-am \
-	uninstall-man uninstall-man1 uninstall-pdf-am \
-	uninstall-prologDATA uninstall-ps-am
+	install-data-am install-dvi install-dvi-am install-exec \
+	install-exec-am install-html install-html-am install-info \
+	install-info-am install-man install-man1 install-pdf \
+	install-pdf-am install-prologDATA install-ps install-ps-am \
+	install-strip installcheck installcheck-am installdirs \
+	installdirs-am maintainer-clean maintainer-clean-aminfo \
+	maintainer-clean-generic mostlyclean mostlyclean-aminfo \
+	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
+	pdf pdf-am ps ps-am tags tags-recursive uninstall uninstall-am \
+	uninstall-binPROGRAMS uninstall-dvi-am uninstall-html-am \
+	uninstall-info-am uninstall-man uninstall-man1 \
+	uninstall-pdf-am uninstall-prologDATA uninstall-ps-am
 
 
 @KPATHSEA_RULE@
@@ -1189,20 +1274,6 @@ $(prologues): squeeze/stamp-squeeze
 
 squeeze/stamp-squeeze:
 	cd squeeze && $(MAKE) $(AM_MAKEFLAGS) stamp-squeeze
-
-install-data-hook:
-	cd $(DESTDIR)$(man1dir) && \
-	  rm -f odvips.1 && \
-	  $(LN_S) dvips.1 odvips.1
-
-install-exec-hook:
-	cd $(DESTDIR)$(bindir) && \
-	  rm -f odvips && \
-	  $(LN_S) dvips$(EXEEXT) odvips$(EXEEXT)
-
-uninstall-hook:
-	rm -f $(DESTDIR)$(man1dir)/odvips.1
-	rm -f $(DESTDIR)$(bindir)/odvips$(EXEEXT)
 
 # in case of an SVN repository
 dist-hook:
