reorganize texk/dvipng
git-svn-id: svn://tug.org/texlive/trunk/Build/source@13752 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/texk/dvipng/configure b/texk/dvipng/configure
--- a/texk/dvipng/configure
+++ b/texk/dvipng/configure
@@ -789,7 +789,6 @@ ac_includes_default="\
 ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
-DVIPNG_VERSION
 have_gif_FALSE
 have_gif_TRUE
 have_ft2_or_t1_FALSE
@@ -823,11 +822,14 @@ KPATHSEA_RULE
 KPATHSEA_DEPEND
 KPATHSEA_LIBS
 KPATHSEA_INCLUDES
+KPSEWHICH
 INSTALL_INFO
 AM_MAKEINFOFLAGS
 POW_LIB
 LIBOBJS
 ALLOCA
+GS
+WARNING_CFLAGS
 CPP
 OTOOL64
 OTOOL
@@ -947,9 +949,11 @@ enable_dependency_tracking
 with_gnu_ld
 enable_libtool_lock
 enable_largefile
+enable_compiler_warnings
 enable_debug
 enable_timing
 with_gs
+enable_selfauto_set
 with_system_kpathsea
 with_kpathsea_includes
 with_kpathsea_libdir
@@ -1616,8 +1620,20 @@ Optional Features:
   --enable-dependency-tracking   do not reject slow dependency extractors
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-largefile     omit support for large files
+  --enable-compiler-warnings=[no|min|yes|max]
+                          Turn on compiler warnings [default: yes if
+                          maintainer-mode, min otherwise]
   --disable-debug         Compile without debug (-d) option
   --enable-timing         Output execution time of dvipng
+  --enable-selfauto-set   This option will make the final binary explicitly
+                          set the $SELFAUTO... variables to make it look as
+                          dvipng is installed in the main texmf tree, even if
+                          it isn't. This is necessary when texmf.cnf only uses
+                          $SELFAUTO... variables and dvipng is not installed
+                          in the texmf tree. Otherwise, dvipng may not be able
+                          to find virtual fonts, or psfonts.map. To find out,
+                          first build the binary and do 'make test'. If the
+                          test fails, you need this switch.
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2143,6 +2159,7 @@ ac_configure="$SHELL $ac_aux_dir/configure"  # Please don't use this var.
 
 
 
+# Common code for all programs using libkpathsea.
 am__api_version='1.11'
 
 # Find a good install program.  We prefer a C program (faster),
@@ -4393,13 +4410,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4396: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4413: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4399: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4416: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4402: output\"" >&5)
+  (eval echo "\"\$as_me:4419: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5605,7 +5622,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5608 "configure"' > conftest.$ac_ext
+  echo '#line 5625 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6960,6 +6977,21 @@ fi
 
 done
 
+# Check whether --enable-compiler-warnings was given.
+if test "${enable_compiler_warnings+set}" = set; then
+  enableval=$enable_compiler_warnings;
+fi
+case $enable_compiler_warnings in
+  no | min | yes | max) : ;;
+  *) if test "x$enable_maintainer_mode" = xyes; then
+  enable_compiler_warnings=yes
+else
+  enable_compiler_warnings=min
+fi
+ ;;
+esac
+
+
 
 if test "`cd $srcdir && pwd`" != "`pwd`"; then
   # Use -I$(srcdir) only when $(srcdir) != ., so that make's output
@@ -7551,11 +7583,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7554: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7586: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7558: \$? = $ac_status" >&5
+   echo "$as_me:7590: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7890,11 +7922,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7893: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7925: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7897: \$? = $ac_status" >&5
+   echo "$as_me:7929: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7995,11 +8027,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7998: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8030: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8002: \$? = $ac_status" >&5
+   echo "$as_me:8034: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8050,11 +8082,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8053: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8085: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8057: \$? = $ac_status" >&5
+   echo "$as_me:8089: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10850,7 +10882,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10853 "configure"
+#line 10885 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10946,7 +10978,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10949 "configure"
+#line 10981 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12949,8 +12981,44 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+{ $as_echo "$as_me:$LINENO: checking what warning flags to pass to the C compiler" >&5
+$as_echo_n "checking what warning flags to pass to the C compiler... " >&6; }
+if test "${kpse_cv_warning_cflags+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  if test "x$enable_compiler_warnings" = xno; then
+  kpse_cv_warning_cflags=
+elif test "x$GCC" = xyes; then
+  kpse_cv_warning_cflags="-Wall -Wunused"
+  if test "x$enable_compiler_warnings" != xmin; then
+    kpse_cv_warning_cflags="$kpse_cv_warning_cflags -Wmissing-prototypes -Wmissing-declarations"
+    case `$CC -dumpversion` in
+  3.4.* | 4.*) kpse_cv_warning_cflags="$kpse_cv_warning_cflags -Wdeclaration-after-statement" ;;
+esac
+
+    if test "x$enable_compiler_warnings" != xyes; then
+      kpse_cv_warning_cflags="$kpse_cv_warning_cflags -Wimplicit -Wparentheses -Wreturn-type"
+      kpse_cv_warning_cflags="$kpse_cv_warning_cflags -Wswitch -Wtrigraphs -Wshadow -Wpointer-arith"
+      kpse_cv_warning_cflags="$kpse_cv_warning_cflags -Wcast-qual -Wcast-align -Wwrite-strings"
+      case `$CC -dumpversion` in
+  3.4.* | 4.*) kpse_cv_warning_cflags="$kpse_cv_warning_cflags -Wold-style-definition" ;;
+esac
+
+    fi
+  fi
+else
+  : # FIXME: warning flags for non-gcc compilers
+fi
+fi
+{ $as_echo "$as_me:$LINENO: result: $kpse_cv_warning_cflags" >&5
+$as_echo "$kpse_cv_warning_cflags" >&6; }
+WARNING_CFLAGS=$kpse_cv_warning_cflags
 
 
+
+
+
+# Configure options for dvipng also shown at the TeX Live top-level.
 ## texk/dvipng/ac/dvipng.ac: configure.ac fragment for the TeX Live subdirectory texk/dvipng/
 ## configure options for dvipng
 # Check whether --enable-debug was given.
@@ -12988,12 +13056,137 @@ _ACEOF
 
 fi
 
+# Checks for programs.
+# For a native TeX Live build '--with-gs' is ignored.
+if test "x$enable_native_texlive_build" = xyes; then
+  with_gs=
+fi
+
+case $with_gs in
+  "" | yes | no) # Extract the first word of "gs", so it can be a program name with args.
+set dummy gs; ac_word=$2
+{ $as_echo "$as_me:$LINENO: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_prog_GS+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$GS"; then
+  ac_cv_prog_GS="$GS" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_GS="gs"
+    $as_echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+GS=$ac_cv_prog_GS
+if test -n "$GS"; then
+  { $as_echo "$as_me:$LINENO: result: $GS" >&5
+$as_echo "$GS" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+ ;;
+  *) # Extract the first word of ""$with_gs"", so it can be a program name with args.
+set dummy "$with_gs"; ac_word=$2
+{ $as_echo "$as_me:$LINENO: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_path_GS+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  case $GS in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GS="$GS" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_GS="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+GS=$ac_cv_path_GS
+if test -n "$GS"; then
+  { $as_echo "$as_me:$LINENO: result: $GS" >&5
+$as_echo "$GS" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+ ;;
+esac
+
+if test -n "$GS"; then
+  GS_WARN=
+{ $as_echo "$as_me:$LINENO: checking whether $GS has the pngalpha device" >&5
+$as_echo_n "checking whether $GS has the pngalpha device... " >&6; }
+if $GS -h | grep pngalpha >/dev/null; then
+  { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+  GS_WARN="Your EPS inclusions will be cropped to the
+        boundingbox, and rendered on an opaque background.
+        Upgrade GhostScript to avoid this."
+        { $as_echo "$as_me:$LINENO: checking whether $GS has the png16m device" >&5
+$as_echo_n "checking whether $GS has the png16m device... " >&6; }
+if $GS -h | grep png16m >/dev/null; then
+  { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+  GS_WARN="Your EPS inclusions may not work.
+        Upgrade/install GhostScript to avoid this."
+fi
+
+fi
+
+if test -n "$GS_WARN"; then
+  { $as_echo "$as_me:$LINENO: WARNING: $GS_WARN" >&5
+$as_echo "$as_me: WARNING: $GS_WARN" >&2;}
+fi
+
+else
+  { $as_echo "$as_me:$LINENO: WARNING: Cannot find GhostScript in your PATH" >&5
+$as_echo "$as_me: WARNING: Cannot find GhostScript in your PATH" >&2;}
+       GS=gs
+fi
+
 
 cat >>confdefs.h <<_ACEOF
-#define GS_PATH "gs"
+#define GS_PATH "$GS"
 _ACEOF
 
 
+# Checks for libraries.
 { $as_echo "$as_me:$LINENO: checking for library containing pow" >&5
 $as_echo_n "checking for library containing pow... " >&6; }
 if test "${ac_cv_search_pow+set}" = set; then
@@ -13169,6 +13362,7 @@ if test "$ac_res" != no; then
 fi
 
 
+# Checks for header files.
 { $as_echo "$as_me:$LINENO: checking for ANSI C header files" >&5
 $as_echo_n "checking for ANSI C header files... " >&6; }
 if test "${ac_cv_header_stdc+set}" = set; then
@@ -13860,6 +14054,7 @@ _ACEOF
 fi
 
 
+# Checks for typedefs, structures, and compiler characteristics.
 { $as_echo "$as_me:$LINENO: checking for an ANSI C-conforming const" >&5
 $as_echo_n "checking for an ANSI C-conforming const... " >&6; }
 if test "${ac_cv_c_const+set}" = set; then
@@ -14369,6 +14564,7 @@ _ACEOF
   esac
 
 
+# Checks for library functions.
 # The Ultrix 4.2 mips builtin alloca declared by alloca.h only works
 # for constant arguments.  Useless!
 { $as_echo "$as_me:$LINENO: checking for working alloca.h" >&5
@@ -16606,6 +16802,7 @@ done
 
 fi
 
+# Documentation-related checks.
 # Extract the first word of "makeinfo", so it can be a program name with args.
 set dummy makeinfo; ac_word=$2
 { $as_echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -16709,6 +16906,131 @@ $as_echo "no" >&6; }
 fi
 
 
+
+# SELFAUTO
+# When dvipng is built as part of the TeX Live tree, the option
+# '--enable-texlive-build' is automatically passed from the top-level.
+# In that case we silently assume '--disable-selfauto-set'.
+test "x$enable_texlive_build" = xyes && enable_selfauto_set=no
+# Check whether --enable-selfauto-set was given.
+if test "${enable_selfauto_set+set}" = set; then
+  enableval=$enable_selfauto_set;  if test "$enableval" = yes ; then
+      { $as_echo "$as_me:$LINENO: checking for \$SELFAUTOLOC" >&5
+$as_echo_n "checking for \$SELFAUTOLOC... " >&6; }
+      SELFAUTOLOC=`kpsewhich -expand-var=\\\$SELFAUTOLOC`
+
+cat >>confdefs.h <<_ACEOF
+#define ENV_SELFAUTOLOC "SELFAUTOLOC=$SELFAUTOLOC"
+_ACEOF
+
+      { $as_echo "$as_me:$LINENO: result: $SELFAUTOLOC" >&5
+$as_echo "$SELFAUTOLOC" >&6; }
+      { $as_echo "$as_me:$LINENO: checking for \$SELFAUTODIR" >&5
+$as_echo_n "checking for \$SELFAUTODIR... " >&6; }
+      SELFAUTODIR=`kpsewhich -expand-var=\\\$SELFAUTODIR`
+
+cat >>confdefs.h <<_ACEOF
+#define ENV_SELFAUTODIR "SELFAUTODIR=$SELFAUTODIR"
+_ACEOF
+
+      { $as_echo "$as_me:$LINENO: result: $SELFAUTODIR" >&5
+$as_echo "$SELFAUTODIR" >&6; }
+      { $as_echo "$as_me:$LINENO: checking for \$SELFAUTOPARENT" >&5
+$as_echo_n "checking for \$SELFAUTOPARENT... " >&6; }
+      SELFAUTOPARENT=`kpsewhich -expand-var=\\\$SELFAUTOPARENT`
+
+cat >>confdefs.h <<_ACEOF
+#define ENV_SELFAUTOPARENT "SELFAUTOPARENT=$SELFAUTOPARENT"
+_ACEOF
+
+      { $as_echo "$as_me:$LINENO: result: $SELFAUTOPARENT" >&5
+$as_echo "$SELFAUTOPARENT" >&6; }
+    fi
+else
+  { $as_echo "$as_me:$LINENO: checking for texmf.cnf" >&5
+$as_echo_n "checking for texmf.cnf... " >&6; }
+  TEXMF_CNF=`kpsewhich texmf.cnf`
+  { $as_echo "$as_me:$LINENO: result: $TEXMF_CNF" >&5
+$as_echo "$TEXMF_CNF" >&6; }
+  # Extract the first word of "kpsewhich", so it can be a program name with args.
+set dummy kpsewhich; ac_word=$2
+{ $as_echo "$as_me:$LINENO: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_path_KPSEWHICH+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  case $KPSEWHICH in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_KPSEWHICH="$KPSEWHICH" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_KPSEWHICH="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+KPSEWHICH=$ac_cv_path_KPSEWHICH
+if test -n "$KPSEWHICH"; then
+  { $as_echo "$as_me:$LINENO: result: $KPSEWHICH" >&5
+$as_echo "$KPSEWHICH" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+  { $as_echo "$as_me:$LINENO: checking for psfonts.map" >&5
+$as_echo_n "checking for psfonts.map... " >&6; }
+  cp $KPSEWHICH .
+  PSFONTS_MAP=`./kpsewhich psfonts.map`
+  rm -f ./kpsewhich
+  if test -n "$PSFONTS_MAP"; then
+    { $as_echo "$as_me:$LINENO: result: $PSFONTS_MAP" >&5
+$as_echo "$PSFONTS_MAP" >&6; }
+  else
+    { $as_echo "$as_me:$LINENO: result: not found from outside the texmf tree" >&5
+$as_echo "not found from outside the texmf tree" >&6; }
+    { $as_echo "$as_me:$LINENO: checking for \$SELFAUTO in texmf.cnf" >&5
+$as_echo_n "checking for \$SELFAUTO in texmf.cnf... " >&6; }
+    if grep SELFAUTO "$TEXMF_CNF" > /dev/null 2> /dev/null; then
+      { $as_echo "$as_me:$LINENO: result: yes
+***************************************************************
+texmf.cnf is using \$SELFAUTO... variables. If you are going to
+install dvipng outside the texmf tree, you may need to use
+--enable-selfauto-set. To find out, do 'make ; make test'. If the test
+is unsuccessful, add the mentioned switch and rebuild.
+***************************************************************" >&5
+$as_echo "yes
+***************************************************************
+texmf.cnf is using \$SELFAUTO... variables. If you are going to
+install dvipng outside the texmf tree, you may need to use
+--enable-selfauto-set. To find out, do 'make ; make test'. If the test
+is unsuccessful, add the mentioned switch and rebuild.
+***************************************************************" >&6; }
+    else
+      { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+    fi
+  fi
+fi
+
+
+# We have to check properties of libraries, either installed (system)
+# libraries or unistalled (possibly libtool) ones from the TeX Live tree.
+# Thus we can not use, e.g., AC_CHECK_LIB(LIB, FUNCTION)
 
 ## _KPSE_INIT: Initialize TL infrastructure
 kpse_BLD=`(cd "./../../." && pwd)`
@@ -18334,7 +18656,7 @@ ${top_builddir}/../../libs/gd/gd.h:
 fi
 
 
-
+# Checks for more libraries.
 kpse_save_CPPFLAGS=$CPPFLAGS
 kpse_save_LIBS=$LIBS
 
@@ -18772,6 +19094,8 @@ fi
 fi
 
 
+# We need enc, cmap, and sfd formats.
+# Introduced together with opentype format (Dec 2003).
 { $as_echo "$as_me:$LINENO: checking whether kpathsea declares the kpse_opentype_format" >&5
 $as_echo_n "checking whether kpathsea declares the kpse_opentype_format... " >&6; }
 if test "${kpse_cv_have_opentype_format+set}" = set; then
@@ -19058,6 +19382,7 @@ else
 fi
 
 
+# Checks for more header files.
 
 
 
@@ -19376,6 +19701,7 @@ fi
 done
 
 
+# Checks for more library functions.
 
 
 
@@ -19496,9 +19822,6 @@ CPPFLAGS=$kpse_save_CPPFLAGS
 LIBS=$kpse_save_LIBS
 
 
-DVIPNG_VERSION=1.12
-
-
 { $as_echo "$as_me:$LINENO: result:
 ** Configuration summary for $PACKAGE_STRING:
 
@@ -19547,7 +19870,7 @@ $as_echo "
 ac_config_headers="$ac_config_headers config.h"
 
 
-ac_config_files="$ac_config_files Makefile"
+ac_config_files="$ac_config_files Makefile help/Makefile doc/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -20472,6 +20795,8 @@ do
     "libtool") CONFIG_COMMANDS="$CONFIG_COMMANDS libtool" ;;
     "config.h") CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+    "help/Makefile") CONFIG_FILES="$CONFIG_FILES help/Makefile" ;;
+    "doc/Makefile") CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
 
   *) { { $as_echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 $as_echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
