dvipng configure update for Mac OS X compatibility
git-svn-id: svn://tug.org/texlive/trunk/Build/source@2635 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/texk/dvipng/configure b/texk/dvipng/configure
--- a/texk/dvipng/configure
+++ b/texk/dvipng/configure
@@ -6510,20 +6510,6 @@ fi
 
 
 
-LIBS="../kpathsea/.libs/libkpathsea.a $LIBS"
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_KPATHSEA_KPATHSEA_H 1
-_ACEOF
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_KPSE_ENC_FORMATS 1
-_ACEOF
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_LIBKPATHSEA 1
-_ACEOF
-
-
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_GDIMAGEPNGEX 1
 _ACEOF
@@ -6701,6 +6687,90 @@ _ACEOF
   LIBS="-lgen $LIBS"
 
 fi
+
+
+LIBS="../kpathsea/.libs/libkpathsea.a $LIBS"
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_KPATHSEA_KPATHSEA_H 1
+_ACEOF
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_KPSE_ENC_FORMATS 1
+_ACEOF
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBKPATHSEA 1
+_ACEOF
+
+
+#
+# Check for ApplicationServices framework (Mac OS X)
+#
+
+
+
+ _cppflags=$CPPFLAGS _ldflags=$LDFLAGS
+ echo "$as_me:$LINENO: checking for Mac OS X ApplicationServices framework" >&5
+echo $ECHO_N "checking for Mac OS X ApplicationServices framework... $ECHO_C" >&6
+ cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <ApplicationServices/ApplicationServices.h>
+
+int
+main ()
+{
+
+ATSFontRef fontRef;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+   echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_APP_SERVICES 1
+_ACEOF
+
+   LIBS="$LIBS -framework ApplicationServices"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
 
           ac_config_headers="$ac_config_headers config.h"
