do not try to count binaries if no bindir
git-svn-id: svn://tug.org/texlive/trunk/Build/source@21121 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/Build b/Build
--- a/Build
+++ b/Build
@@ -120,16 +120,20 @@ cd $TL_WORKDIR || exit 1
 } 2>&1 | tee build.log
  
 
-# report the number of binaries built.
+# if we have a bindir, report the number of binaries built.
 bindir=$TL_INSTALL_DEST/bin
-count=`find $bindir \! -type d -print | wc -l`
-if test "$count" -gt 0; then
-  echo
-  echo "$0: $count executables in $bindir."
-else
-  echo "$0: Build failed, no executables under $bindir."
-  exit 1
-fi | tee -a build.log
+if test -d "$bindir"; then
+  count=`find "$bindir" \! -type d -print | wc -l`
+  if test "$count" -gt 0; then
+    echo
+    echo "$0: $count executables in $bindir."
+  else
+    echo "$0: Build failed, no executables under $bindir."
+    exit 1
+  fi | tee -a build.log
+# if no bindir, perhaps they specified --prefix; don't worry.
+# Any errors will have been duly reported anyway.
+fi
 
 echo done `date` | tee -a build.log
 
