renamed the --with-external-clisp[=PATH] configure option to --with-clisp[=PATH]
git-svn-id: svn://tug.org/texlive/trunk/Build/source@7118 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/utils/xindy/configure b/utils/xindy/configure
--- a/utils/xindy/configure
+++ b/utils/xindy/configure
@@ -1315,8 +1315,7 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-external-clisp[=PATH]
-                          Use the external CLISP binary instead of re-building
+  --with-clisp[=PATH]     Use the existing CLISP binary instead of re-building
                           CLISP from source in the rte/ directory
 
 Some influential environment variables:
@@ -3835,14 +3834,14 @@ fi
 
 
 
-# Check whether --with-external-clisp was given.
-if test "${with_external_clisp+set}" = set; then
-  withval=$with_external_clisp;
+# Check whether --with-clisp was given.
+if test "${with_clisp+set}" = set; then
+  withval=$with_clisp;
 fi
 
 
 CLISP=
-if test "x$with_external_clisp" = xyes; then
+if test "x$with_clisp" = xyes; then
   # Extract the first word of "clisp", so it can be a program name with args.
 set dummy clisp; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -3884,21 +3883,21 @@ fi
 
 
   if test -z "$CLISP"; then
-    { { echo "$as_me:$LINENO: error: --with-external-clisp specified, but clisp binary not found in PATH" >&5
-echo "$as_me: error: --with-external-clisp specified, but clisp binary not found in PATH" >&2;}
+    { { echo "$as_me:$LINENO: error: --with-clisp specified, but clisp binary not found in PATH" >&5
+echo "$as_me: error: --with-clisp specified, but clisp binary not found in PATH" >&2;}
    { (exit 1); exit 1; }; }
   fi
-elif test "x$with_external_clisp" = xno; then
+elif test "x$with_clisp" = xno; then
   if test -d "$srcdir/rte/clisp-2.43"; then
     { echo "$as_me:$LINENO: Using internal clisp" >&5
 echo "$as_me: Using internal clisp" >&6;}
   else
-    { { echo "$as_me:$LINENO: error: --without-external-clisp specified, but clisp source directory not found at $srcdir/rte/clisp-2.43" >&5
-echo "$as_me: error: --without-external-clisp specified, but clisp source directory not found at $srcdir/rte/clisp-2.43" >&2;}
+    { { echo "$as_me:$LINENO: error: --without-clisp specified, but clisp source directory not found at $srcdir/rte/clisp-2.43" >&5
+echo "$as_me: error: --without-clisp specified, but clisp source directory not found at $srcdir/rte/clisp-2.43" >&2;}
    { (exit 1); exit 1; }; }
   fi
-elif test -n "$with_external_clisp"; then
-  CLISP="$with_external_clisp"
+elif test -n "$with_clisp"; then
+  CLISP="$with_clisp"
 else
   # Extract the first word of "clisp", so it can be a program name with args.
 set dummy clisp; ac_word=$2
@@ -3970,8 +3969,6 @@ echo "$as_me: error: expected directory is not found: $CLISP_LIB/full" >&2;}
   test -d "$CLISP_LIB/linkkit" || { { echo "$as_me:$LINENO: error: expected directory is not found: $CLISP_LIB/linkkit" >&5
 echo "$as_me: error: expected directory is not found: $CLISP_LIB/linkkit" >&2;}
    { (exit 1); exit 1; }; }
-  { echo "$as_me:$LINENO: Using external clisp" >&5
-echo "$as_me: Using external clisp" >&6;}
 fi
 
  if test -n "$CLISP"; then
