stop if LEX (flex or lex) is not found during configure
git-svn-id: svn://tug.org/texlive/trunk/Build/source@7166 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/utils/xindy/configure b/utils/xindy/configure
--- a/utils/xindy/configure
+++ b/utils/xindy/configure
@@ -3678,6 +3678,10 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+test "x$LEX" != "x:" || { { echo "$as_me:$LINENO: error: flex or lex is required, but not found" >&5
+echo "$as_me: error: flex or lex is required, but not found" >&2;}
+   { (exit 1); exit 1; }; }
+
 # Check whether --enable-make-rules was given.
 if test "${enable_make_rules+set}" = set; then
   enableval=$enable_make_rules;
