autoreconf
git-svn-id: svn://tug.org/texlive/trunk/Build/source@10982 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/utils/xindy/configure b/utils/xindy/configure
--- a/utils/xindy/configure
+++ b/utils/xindy/configure
@@ -695,6 +695,7 @@ am__fastdepCC_FALSE
 LEX
 LEX_OUTPUT_ROOT
 LEXLIB
+CONVERT_FROM_UTF8
 TETEX_BUILD_TRUE
 TETEX_BUILD_FALSE
 latex
@@ -1323,6 +1324,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-clisp=...        Use the specified location of the clisp executable
                           (default is search in PATH)
+  --with-xindy-recode     Use `recode' instead of `iconv' (default is NO)
 
 Some influential environment variables:
   CC          C compiler command
@@ -3703,6 +3705,60 @@ if test "${with_clisp+set}" = set; then
 fi
 
 
+# Check whether --with-xindy-recode was given.
+if test "${with_xindy_recode+set}" = set; then
+  withval=$with_xindy_recode;
+fi
+
+
+if test "x$with_xindy_recode" = xno; then
+  CONVERT_FROM_UTF8="iconv -f UTF-8 -t "
+else
+  # Extract the first word of "recode", so it can be a program name with args.
+set dummy recode; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_CONVERT_FROM_UTF8+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$CONVERT_FROM_UTF8"; then
+  ac_cv_prog_CONVERT_FROM_UTF8="$CONVERT_FROM_UTF8" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_CONVERT_FROM_UTF8="recode UTF-8.."
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+CONVERT_FROM_UTF8=$ac_cv_prog_CONVERT_FROM_UTF8
+if test -n "$CONVERT_FROM_UTF8"; then
+  { echo "$as_me:$LINENO: result: $CONVERT_FROM_UTF8" >&5
+echo "${ECHO_T}$CONVERT_FROM_UTF8" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  if test "x$CONVERT_FROM_UTF8" != "xrecode UTF-8.."; then
+    { { echo "$as_me:$LINENO: error: --with-xindy-recode specified, but \`recode' not found" >&5
+echo "$as_me: error: --with-xindy-recode specified, but \`recode' not found" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+fi
+
+
 if test "x$enable_tetex_build" = xyes -a "x$datadir" = "x$prefix"; then
   { echo "$as_me:$LINENO: Using installation layout for TeX Live" >&5
 echo "$as_me: Using installation layout for TeX Live" >&6;}
@@ -5803,6 +5859,7 @@ am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
 LEX!$LEX$ac_delim
 LEX_OUTPUT_ROOT!$LEX_OUTPUT_ROOT$ac_delim
 LEXLIB!$LEXLIB$ac_delim
+CONVERT_FROM_UTF8!$CONVERT_FROM_UTF8$ac_delim
 TETEX_BUILD_TRUE!$TETEX_BUILD_TRUE$ac_delim
 TETEX_BUILD_FALSE!$TETEX_BUILD_FALSE$ac_delim
 latex!$latex$ac_delim
@@ -5818,7 +5875,6 @@ LISP_RUN!$LISP_RUN$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
-build!$build$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -5860,6 +5916,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+build!$build$ac_delim
 build_cpu!$build_cpu$ac_delim
 build_vendor!$build_vendor$ac_delim
 build_os!$build_os$ac_delim
@@ -5871,7 +5928,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 9; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 10; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
