somewhat more general way to create symlinks for linked scripts using build-aux/relpath
git-svn-id: svn://tug.org/texlive/trunk/Build/source@24137 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/texk/tex4htk/Makefile.in b/texk/tex4htk/Makefile.in
--- a/texk/tex4htk/Makefile.in
+++ b/texk/tex4htk/Makefile.in
@@ -256,6 +256,23 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 ACLOCAL_AMFLAGS = -I ../../m4
+EXTRA_DIST = java ../../build-aux/relpath dbcontext dblatex dbmcontext \
+	dbmex dbmlatex dbmmex dbmtex dbmtexi dbmxelatex dbmxetex dbtex \
+	dbtexi dbxelatex dbxetex demo.tex escontext eslatex esmex \
+	estex estexi esxelatex esxetex jh1context jh1latex jh1mex \
+	jh1tex jh1texi jh1xelatex jh1xetex jhcontext jhlatex jhmex \
+	jhtex jhtexi jhxelatex jhxetex jmcontext jmlatex jmmex jmtex \
+	jmtexi jmxelatex jmxetex jscontext jslatex jsmex jstex jstexi \
+	jsxelatex jsxetex mzcontext mzlatex mzmex mztex mztexi \
+	mzxelatex mzxetex oocontext oolatex oomex ootex ootexi \
+	ooxelatex ooxetex teicontext teilatex teimcontext teimex \
+	teimlatex teimmex teimtex teimtexi teimxelatex teimxetex \
+	teitex teitexi teixelatex teixetex test.tex test1.tex \
+	testa.tex testb.tex uxhcontext uxhlatex uxhmex uxhtex uxhtexi \
+	uxhxelatex uxhxetex wcontext wlatex wmex wtex wtexi wxelatex \
+	wxetex xhcontext xhlatex xhmcontext xhmex xhmlatex xhmmex \
+	xhmtex xhmtexi xhmxelatex xhmxetex xhtex xhtexi xhxelatex \
+	xhxetex xv4ht.java
 INCLUDES = $(KPATHSEA_INCLUDES)
 AM_CPPFLAGS = -DANSI -DKPATHSEA
 AM_CFLAGS = $(WARNING_CFLAGS)
@@ -273,120 +290,6 @@ texmfdir = ${prefix}/$(scriptsdir)
 dist_texmf_SCRIPTS = $(perl_scripts:=.pl) $(shell_scripts:=.sh)
 @WIN32_TRUE@dist_bin_SCRIPTS = $(shell_scripts:=.bat)
 CLEANFILES = $(nodist_bin_SCRIPTS)
-EXTRA_DIST = \
-	dbcontext \
-	dblatex \
-	dbmcontext \
-	dbmex \
-	dbmlatex \
-	dbmmex \
-	dbmtex \
-	dbmtexi \
-	dbmxelatex \
-	dbmxetex \
-	dbtex \
-	dbtexi \
-	dbxelatex \
-	dbxetex \
-	demo.tex \
-	escontext \
-	eslatex \
-	esmex \
-	estex \
-	estexi \
-	esxelatex \
-	esxetex \
-	java \
-	jh1context \
-	jh1latex \
-	jh1mex \
-	jh1tex \
-	jh1texi \
-	jh1xelatex \
-	jh1xetex \
-	jhcontext \
-	jhlatex \
-	jhmex \
-	jhtex \
-	jhtexi \
-	jhxelatex \
-	jhxetex \
-	jmcontext \
-	jmlatex \
-	jmmex \
-	jmtex \
-	jmtexi \
-	jmxelatex \
-	jmxetex \
-	jscontext \
-	jslatex \
-	jsmex \
-	jstex \
-	jstexi \
-	jsxelatex \
-	jsxetex \
-	mzcontext \
-	mzlatex \
-	mzmex \
-	mztex \
-	mztexi \
-	mzxelatex \
-	mzxetex \
-	oocontext \
-	oolatex \
-	oomex \
-	ootex \
-	ootexi \
-	ooxelatex \
-	ooxetex \
-	teicontext \
-	teilatex \
-	teimcontext \
-	teimex \
-	teimlatex \
-	teimmex \
-	teimtex \
-	teimtexi \
-	teimxelatex \
-	teimxetex \
-	teitex \
-	teitexi \
-	teixelatex \
-	teixetex \
-	test.tex \
-	test1.tex \
-	testa.tex \
-	testb.tex \
-	uxhcontext \
-	uxhlatex \
-	uxhmex \
-	uxhtex \
-	uxhtexi \
-	uxhxelatex \
-	uxhxetex \
-	wcontext \
-	wlatex \
-	wmex \
-	wtex \
-	wtexi \
-	wxelatex \
-	wxetex \
-	xhcontext \
-	xhlatex \
-	xhmcontext \
-	xhmex \
-	xhmlatex \
-	xhmmex \
-	xhmtex \
-	xhmtexi \
-	xhmxelatex \
-	xhmxetex \
-	xhtex \
-	xhtexi \
-	xhxelatex \
-	xhxetex \
-	xv4ht.java
-
 all: c-auto.h
 	$(MAKE) $(AM_MAKEFLAGS) all-am
 
@@ -970,13 +873,15 @@ uninstall-am: uninstall-binPROGRAMS uninstall-dist_binSCRIPTS \
 	uninstall-hook uninstall-nodist_binSCRIPTS
 
 
+# in case of an SVN repository
+dist-hook:
+	rm -rf `find $(distdir) -name .svn`
+
 $(t4ht_OBJECTS) $(tex4ht_OBJECTS): $(KPATHSEA_DEPEND)
 
 @KPATHSEA_RULE@
-
-#
 .PHONY: install-lua-links install-perl-links install-shell-links \
-	install-links make-links uninstall-links
+	install-links uninstall-links
 @WIN32_TRUE@@WIN32_WRAP_TRUE@$(wrappers): $(runscript)
 @WIN32_TRUE@@WIN32_WRAP_TRUE@	$(LN_S) $(runscript) $@
 
@@ -989,21 +894,18 @@ install-perl-links:
 install-shell-links:
 @WIN32_FALSE@	$(MAKE) $(AM_MAKEFLAGS) TYPE=shell EXT=sh install-links
 
-# We support both multiplatform and non-multiplatform builds.
+# We support native builds, multiplatform or not, as well as distro builds.
 install-links:
-	case "$(bindir)" in \
-	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
-	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=../.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
-	  *) echo "strange directory '$(bindir)' for linked $(TYPE) scripts" >&2; \
-	     exit 1;; \
-	esac
-
-make-links:
-	@cd $(DESTDIR)$(bindir) && \
+	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(prefix)'`; \
+	if test -z "$$REL"; then \
+	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+	  exit 1; \
+	fi; \
+	cd $(DESTDIR)$(bindir) && \
 	  for f in $($(TYPE)_scripts); do \
 	    rm -f $$f; \
-	    echo "creating link '$$f' -> '$(REL)/$(scriptsdir)/$$f.$(EXT)'"; \
-	    $(LN_S) $(REL)/$(scriptsdir)/$$f.$(EXT) $$f || exit 1; \
+	    echo "creating link '$$f' -> '$$REL/$(scriptsdir)/$$f.$(EXT)'"; \
+	    $(LN_S) $$REL/$(scriptsdir)/$$f.$(EXT) $$f || exit 1; \
 	  done  
 
 uninstall-links:
@@ -1014,10 +916,6 @@ uninstall-links:
 
 install-data-hook: install-perl-links install-shell-links
 uninstall-hook: uninstall-links
-
-# in case of an SVN repository
-dist-hook:
-	rm -rf `find $(distdir) -name .svn`
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
diff --git a/texk/texlive/linked_scripts/Makefile.am b/texk/texlive/linked_scripts/Makefile.am
--- a/texk/texlive/linked_scripts/Makefile.am
+++ b/texk/texlive/linked_scripts/Makefile.am
@@ -11,8 +11,12 @@ if MAINTAINER_MODE
 all-local: scripts.tmp
 scripts.tmp: Makefile
 	echo "Create $@"
-	@echo "texmf_scripts='$(nobase_dist_texmf_scripts_SCRIPTS)'" >$@
-	@echo "texmf_dist_scripts='$(nobase_dist_texmf_dist_scripts_SCRIPTS)'" >>$@
+	@echo "texmf_scripts='" >$@
+	@for f in $(nobase_dist_texmf_scripts_SCRIPTS); do echo "$$f"; done >>$@
+	@echo "'" >>$@
+	@echo "texmf_dist_scripts='" >>$@
+	@for f in $(nobase_dist_texmf_dist_scripts_SCRIPTS); do echo "$$f"; done >>$@
+	@echo "'" >>$@
 	cmp -s $(srcdir)/scripts.lst $@ || cp -f $@ $(srcdir)/scripts.lst
 else !MAINTAINER_MODE
 all-local:
@@ -152,8 +156,10 @@ bin_links = \
 # written the auto-update to ensure linked_scripts is actually up to date
 # with the masters in Master/texmf*/scripts, but one day.
 #
-# We support both multiplatform and non-multiplatform builds.
+# We support native builds, multiplatform or not, as well as distro builds.
 #
+EXTRA_DIST += ../../../build-aux/relpath
+relpath = $(SHELL) $(top_srcdir)/../../build-aux/relpath
 runscript = $(top_srcdir)/w32_wrapper/runscript.exe
 install-data-hook:
 if WIN32
@@ -168,33 +174,28 @@ if WIN32
 	  $(INSTALL_SCRIPT) $(runscript) $(DESTDIR)$(bindir)/$$link.exe || exit 1; \
 	done
 else !WIN32
-	case "$(bindir)" in \
-	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=.. install-links;; \
-	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=../.. install-links;; \
-	  *) echo "strange directory '$(bindir)' for linked scripts" >&2; \
-	     exit 1;; \
-	esac
-endif !WIN32
-
 ## Name the link as the basename, removing any extension,
 ## except for listings-ext.sh, which is documented as that name.
 ## Downcase for the sake of TeXcount.pl -> texcount.
-.PHONY: install-links
-install-links:
-	@cd $(DESTDIR)$(bindir) && \
+	@REL=`$(relpath) '$(DESTDIR)' '$(bindir)' '$(prefix)'`; \
+	if test -z "$$REL"; then \
+	  echo 'unable to compute relative path for linked scripts' >&2; \
+	  exit 1; \
+	fi; \
+	cd $(DESTDIR)$(bindir) && \
 	  for s in $(nobase_dist_texmf_scripts_SCRIPTS); do \
 	    target=`basename $$s | sed 's,\.[^/]*$$,,' | tr '[A-Z]' '[a-z]'`; \
 	    rm -f $$target; \
-	    echo "creating link '$$target' -> '$(REL)/texmf/scripts/$$s'"; \
-	    $(LN_S) $(REL)/texmf/scripts/$$s $$target || exit 1; \
+	    echo "creating link '$$target' -> '$$REL/texmf/scripts/$$s'"; \
+	    $(LN_S) $$REL/texmf/scripts/$$s $$target || exit 1; \
 	  done && \
 	  for s in $(nobase_dist_texmf_dist_scripts_SCRIPTS); do \
 	    target=`basename $$s | tr '[A-Z]' '[a-z]'`; \
 	    echo "$$s" | grep listings-ext.sh >/dev/null \
 	    || target=`echo $$target | sed 's,\.[^/]*$$,,'`; \
 	    rm -f $$target; \
-	    echo "creating link '$$target' -> '$(REL)/texmf-dist/scripts/$$s'"; \
-	    $(LN_S) $(REL)/texmf-dist/scripts/$$s $$target || exit 1; \
+	    echo "creating link '$$target' -> '$$REL/texmf-dist/scripts/$$s'"; \
+	    $(LN_S) $$REL/texmf-dist/scripts/$$s $$target || exit 1; \
 	  done && \
 	  for s in $(bin_links); do \
 	    link=`echo $$s | sed 's,.*:,,'`; \
@@ -204,11 +205,15 @@ install-links:
 	    $(LN_S) $$file $$link || exit 1; \
 	  done && \
 	  rm -f man && \
-	  if test -d $(REL)/texmf/doc/man; then \
-	    echo "creating link 'man' -> '$(REL)/texmf/doc/man'" && \
-	    (ln -s $(REL)/texmf/doc/man man || :); \
+	  if test -d $$REL/texmf/doc/man; then \
+	    echo "creating link 'man' -> '$$REL/texmf/doc/man'" && \
+	    (ln -s $$REL/texmf/doc/man man || :); \
 	  else :; fi
 ## man dir link for those mans which can use it.
+endif !WIN32
+
+.PHONY: install-links
+install-links:
 
 ## For WIN32 (MinGW or native) we have wrapper binaries with .exe,
 ## for Cygwin and Unix we have symlinks without .exe.
diff --git a/texk/texlive/linked_scripts/Makefile.in b/texk/texlive/linked_scripts/Makefile.in
--- a/texk/texlive/linked_scripts/Makefile.in
+++ b/texk/texlive/linked_scripts/Makefile.in
@@ -159,7 +159,28 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 DISTCLEANFILES = scripts.tmp
-EXTRA_DIST = scripts.lst
+
+# The idea is to install the scripts themselves in texmf*/scripts, and
+# have bin/arch/foo be a symlink to, say,
+# ../../texmf-dist/scripts/foo/foo.pl.  That way we save a bit of disk
+# space, but much more importantly omit duplication, and most
+# importantly of all make it possible to invoke the same Perl script on
+# Windows (see ../w32_wrapper).
+#
+# The installation into texmf*/scripts is ideally done with ctan2tl.
+# The copy of the wrapper for Windows is done by hand, but (todo)
+# could/should also be done by ctan2tl.  The check-wrapper-consistency
+# script at least checks after the fact for problems.
+#
+# We also keep a copy of all the scripts here and install into the runtime.
+# This is purely for other distro builders, so symlinks are not dangling in
+# the inst/bin dir (it is meaningless in native TL).  We have not yet
+# written the auto-update to ensure linked_scripts is actually up to date
+# with the masters in Master/texmf*/scripts, but one day.
+#
+# We support native builds, multiplatform or not, as well as distro builds.
+#
+EXTRA_DIST = scripts.lst ../../../build-aux/relpath
 bin_SCRIPTS = 
 
 # Copies of these scripts exist here for the sake of avoiding
@@ -274,27 +295,7 @@ bin_links = \
 	epstopdf:repstopdf \
 	pdfcrop:rpdfcrop
 
-
-# The idea is to install the scripts themselves in texmf*/scripts, and
-# have bin/arch/foo be a symlink to, say,
-# ../../texmf-dist/scripts/foo/foo.pl.  That way we save a bit of disk
-# space, but much more importantly omit duplication, and most
-# importantly of all make it possible to invoke the same Perl script on
-# Windows (see ../w32_wrapper).
-#
-# The installation into texmf*/scripts is ideally done with ctan2tl.
-# The copy of the wrapper for Windows is done by hand, but (todo)
-# could/should also be done by ctan2tl.  The check-wrapper-consistency
-# script at least checks after the fact for problems.
-#
-# We also keep a copy of all the scripts here and install into the runtime.
-# This is purely for other distro builders, so symlinks are not dangling in
-# the inst/bin dir (it is meaningless in native TL).  We have not yet
-# written the auto-update to ensure linked_scripts is actually up to date
-# with the masters in Master/texmf*/scripts, but one day.
-#
-# We support both multiplatform and non-multiplatform builds.
-#
+relpath = $(SHELL) $(top_srcdir)/../../build-aux/relpath
 runscript = $(top_srcdir)/w32_wrapper/runscript.exe
 @WIN32_TRUE@WINEXT = $(EXEEXT)
 all: all-am
@@ -608,8 +609,12 @@ uninstall-am: uninstall-binSCRIPTS \
 @MAINTAINER_MODE_TRUE@all-local: scripts.tmp
 @MAINTAINER_MODE_TRUE@scripts.tmp: Makefile
 @MAINTAINER_MODE_TRUE@	echo "Create $@"
-@MAINTAINER_MODE_TRUE@	@echo "texmf_scripts='$(nobase_dist_texmf_scripts_SCRIPTS)'" >$@
-@MAINTAINER_MODE_TRUE@	@echo "texmf_dist_scripts='$(nobase_dist_texmf_dist_scripts_SCRIPTS)'" >>$@
+@MAINTAINER_MODE_TRUE@	@echo "texmf_scripts='" >$@
+@MAINTAINER_MODE_TRUE@	@for f in $(nobase_dist_texmf_scripts_SCRIPTS); do echo "$$f"; done >>$@
+@MAINTAINER_MODE_TRUE@	@echo "'" >>$@
+@MAINTAINER_MODE_TRUE@	@echo "texmf_dist_scripts='" >>$@
+@MAINTAINER_MODE_TRUE@	@for f in $(nobase_dist_texmf_dist_scripts_SCRIPTS); do echo "$$f"; done >>$@
+@MAINTAINER_MODE_TRUE@	@echo "'" >>$@
 @MAINTAINER_MODE_TRUE@	cmp -s $(srcdir)/scripts.lst $@ || cp -f $@ $(srcdir)/scripts.lst
 @MAINTAINER_MODE_FALSE@all-local:
 install-data-hook:
@@ -623,42 +628,41 @@ install-data-hook:
 @WIN32_TRUE@	  echo "$(INSTALL_SCRIPT) '$(runscript)' '$(DESTDIR)$(bindir)/$$link.exe'"; \
 @WIN32_TRUE@	  $(INSTALL_SCRIPT) $(runscript) $(DESTDIR)$(bindir)/$$link.exe || exit 1; \
 @WIN32_TRUE@	done
-@WIN32_FALSE@	case "$(bindir)" in \
-@WIN32_FALSE@	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=.. install-links;; \
-@WIN32_FALSE@	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=../.. install-links;; \
-@WIN32_FALSE@	  *) echo "strange directory '$(bindir)' for linked scripts" >&2; \
-@WIN32_FALSE@	     exit 1;; \
-@WIN32_FALSE@	esac
+@WIN32_FALSE@	@REL=`$(relpath) '$(DESTDIR)' '$(bindir)' '$(prefix)'`; \
+@WIN32_FALSE@	if test -z "$$REL"; then \
+@WIN32_FALSE@	  echo 'unable to compute relative path for linked scripts' >&2; \
+@WIN32_FALSE@	  exit 1; \
+@WIN32_FALSE@	fi; \
+@WIN32_FALSE@	cd $(DESTDIR)$(bindir) && \
+@WIN32_FALSE@	  for s in $(nobase_dist_texmf_scripts_SCRIPTS); do \
+@WIN32_FALSE@	    target=`basename $$s | sed 's,\.[^/]*$$,,' | tr '[A-Z]' '[a-z]'`; \
+@WIN32_FALSE@	    rm -f $$target; \
+@WIN32_FALSE@	    echo "creating link '$$target' -> '$$REL/texmf/scripts/$$s'"; \
+@WIN32_FALSE@	    $(LN_S) $$REL/texmf/scripts/$$s $$target || exit 1; \
+@WIN32_FALSE@	  done && \
+@WIN32_FALSE@	  for s in $(nobase_dist_texmf_dist_scripts_SCRIPTS); do \
+@WIN32_FALSE@	    target=`basename $$s | tr '[A-Z]' '[a-z]'`; \
+@WIN32_FALSE@	    echo "$$s" | grep listings-ext.sh >/dev/null \
+@WIN32_FALSE@	    || target=`echo $$target | sed 's,\.[^/]*$$,,'`; \
+@WIN32_FALSE@	    rm -f $$target; \
+@WIN32_FALSE@	    echo "creating link '$$target' -> '$$REL/texmf-dist/scripts/$$s'"; \
+@WIN32_FALSE@	    $(LN_S) $$REL/texmf-dist/scripts/$$s $$target || exit 1; \
+@WIN32_FALSE@	  done && \
+@WIN32_FALSE@	  for s in $(bin_links); do \
+@WIN32_FALSE@	    link=`echo $$s | sed 's,.*:,,'`; \
+@WIN32_FALSE@	    file=`echo $$s | sed 's,:.*,,'`; \
+@WIN32_FALSE@	    rm -f $$link; \
+@WIN32_FALSE@	    echo "creating link '$$link' -> '$$file'"; \
+@WIN32_FALSE@	    $(LN_S) $$file $$link || exit 1; \
+@WIN32_FALSE@	  done && \
+@WIN32_FALSE@	  rm -f man && \
+@WIN32_FALSE@	  if test -d $$REL/texmf/doc/man; then \
+@WIN32_FALSE@	    echo "creating link 'man' -> '$$REL/texmf/doc/man'" && \
+@WIN32_FALSE@	    (ln -s $$REL/texmf/doc/man man || :); \
+@WIN32_FALSE@	  else :; fi
 
 .PHONY: install-links
 install-links:
-	@cd $(DESTDIR)$(bindir) && \
-	  for s in $(nobase_dist_texmf_scripts_SCRIPTS); do \
-	    target=`basename $$s | sed 's,\.[^/]*$$,,' | tr '[A-Z]' '[a-z]'`; \
-	    rm -f $$target; \
-	    echo "creating link '$$target' -> '$(REL)/texmf/scripts/$$s'"; \
-	    $(LN_S) $(REL)/texmf/scripts/$$s $$target || exit 1; \
-	  done && \
-	  for s in $(nobase_dist_texmf_dist_scripts_SCRIPTS); do \
-	    target=`basename $$s | tr '[A-Z]' '[a-z]'`; \
-	    echo "$$s" | grep listings-ext.sh >/dev/null \
-	    || target=`echo $$target | sed 's,\.[^/]*$$,,'`; \
-	    rm -f $$target; \
-	    echo "creating link '$$target' -> '$(REL)/texmf-dist/scripts/$$s'"; \
-	    $(LN_S) $(REL)/texmf-dist/scripts/$$s $$target || exit 1; \
-	  done && \
-	  for s in $(bin_links); do \
-	    link=`echo $$s | sed 's,.*:,,'`; \
-	    file=`echo $$s | sed 's,:.*,,'`; \
-	    rm -f $$link; \
-	    echo "creating link '$$link' -> '$$file'"; \
-	    $(LN_S) $$file $$link || exit 1; \
-	  done && \
-	  rm -f man && \
-	  if test -d $(REL)/texmf/doc/man; then \
-	    echo "creating link 'man' -> '$(REL)/texmf/doc/man'" && \
-	    (ln -s $(REL)/texmf/doc/man man || :); \
-	  else :; fi
 
 uninstall-hook:
 	@for s in $(nobase_dist_texmf_scripts_SCRIPTS) $(nobase_dist_texmf_dist_scripts_SCRIPTS); do \
diff --git a/utils/chktex/Makefile.in b/utils/chktex/Makefile.in
--- a/utils/chktex/Makefile.in
+++ b/utils/chktex/Makefile.in
@@ -223,8 +223,8 @@ top_srcdir = @top_srcdir@
 #
 #************************************************************************
 ACLOCAL_AMFLAGS = -I ../../m4
-EXTRA_DIST = $(CHKTEX_TREE) $(CHKTEX_TREE)-PATCHES ChkTeX.tex \
-	chktex.test
+EXTRA_DIST = $(CHKTEX_TREE) $(CHKTEX_TREE)-PATCHES \
+	../../build-aux/relpath ChkTeX.tex chktex.test
 AM_CPPFLAGS = -DNO_KPSE_DLL
 AM_CFLAGS = $(WARNING_CFLAGS)
 chktex_SOURCES = \
@@ -1103,10 +1103,8 @@ uninstall-man: uninstall-man1
 # in case of an SVN repository
 dist-hook:
 	rm -rf `find $(distdir) -name .svn`
-
-#
 .PHONY: install-lua-links install-perl-links install-shell-links \
-	install-links make-links uninstall-links
+	install-links uninstall-links
 @WIN32_TRUE@@WIN32_WRAP_TRUE@$(wrappers): $(runscript)
 @WIN32_TRUE@@WIN32_WRAP_TRUE@	$(LN_S) $(runscript) $@
 
@@ -1119,21 +1117,18 @@ install-perl-links:
 install-shell-links:
 @WIN32_FALSE@	$(MAKE) $(AM_MAKEFLAGS) TYPE=shell EXT=sh install-links
 
-# We support both multiplatform and non-multiplatform builds.
+# We support native builds, multiplatform or not, as well as distro builds.
 install-links:
-	case "$(bindir)" in \
-	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
-	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=../.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
-	  *) echo "strange directory '$(bindir)' for linked $(TYPE) scripts" >&2; \
-	     exit 1;; \
-	esac
-
-make-links:
-	@cd $(DESTDIR)$(bindir) && \
+	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(prefix)'`; \
+	if test -z "$$REL"; then \
+	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+	  exit 1; \
+	fi; \
+	cd $(DESTDIR)$(bindir) && \
 	  for f in $($(TYPE)_scripts); do \
 	    rm -f $$f; \
-	    echo "creating link '$$f' -> '$(REL)/$(scriptsdir)/$$f.$(EXT)'"; \
-	    $(LN_S) $(REL)/$(scriptsdir)/$$f.$(EXT) $$f || exit 1; \
+	    echo "creating link '$$f' -> '$$REL/$(scriptsdir)/$$f.$(EXT)'"; \
+	    $(LN_S) $$REL/$(scriptsdir)/$$f.$(EXT) $$f || exit 1; \
 	  done  
 
 uninstall-links:
diff --git a/utils/xindy/Makefile.in b/utils/xindy/Makefile.in
--- a/utils/xindy/Makefile.in
+++ b/utils/xindy/Makefile.in
@@ -248,7 +248,8 @@ EXTRA_DIST = README-clisp $(XINDY_TREE)-PATCHES $(XINDY_TREE)/AUTHORS \
 	$(XINDY_TREE)/configure.ac \
 	$(XINDY_TREE)/make-rules/alphabets/Makefile.am.not-yet \
 	$(XINDY_TREE)/make-rules/alphabets/lang.defs \
-	$(XINDY_TREE)/make-rules/alphabets/mk-lang.sh
+	$(XINDY_TREE)/make-rules/alphabets/mk-lang.sh \
+	../../build-aux/relpath
 SUBDIRS = . $(XINDY_TREE)
 DIST_SUBDIRS = $(SUBDIRS)
 perl_scripts = texindy xindy
@@ -818,10 +819,8 @@ all-local: config.force
 config.force:
 	echo timestamp >config.force
 	$(SHELL) ./config.status --recheck
-
-#
 .PHONY: install-lua-links install-perl-links install-shell-links \
-	install-links make-links uninstall-links
+	install-links uninstall-links
 @WIN32_TRUE@@WIN32_WRAP_TRUE@$(wrappers): $(runscript)
 @WIN32_TRUE@@WIN32_WRAP_TRUE@	$(LN_S) $(runscript) $@
 
@@ -834,21 +833,18 @@ install-perl-links:
 install-shell-links:
 @WIN32_FALSE@	$(MAKE) $(AM_MAKEFLAGS) TYPE=shell EXT=sh install-links
 
-# We support both multiplatform and non-multiplatform builds.
+# We support native builds, multiplatform or not, as well as distro builds.
 install-links:
-	case "$(bindir)" in \
-	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
-	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=../.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
-	  *) echo "strange directory '$(bindir)' for linked $(TYPE) scripts" >&2; \
-	     exit 1;; \
-	esac
-
-make-links:
-	@cd $(DESTDIR)$(bindir) && \
+	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(prefix)'`; \
+	if test -z "$$REL"; then \
+	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+	  exit 1; \
+	fi; \
+	cd $(DESTDIR)$(bindir) && \
 	  for f in $($(TYPE)_scripts); do \
 	    rm -f $$f; \
-	    echo "creating link '$$f' -> '$(REL)/$(scriptsdir)/$$f.$(EXT)'"; \
-	    $(LN_S) $(REL)/$(scriptsdir)/$$f.$(EXT) $$f || exit 1; \
+	    echo "creating link '$$f' -> '$$REL/$(scriptsdir)/$$f.$(EXT)'"; \
+	    $(LN_S) $$REL/$(scriptsdir)/$$f.$(EXT) $$f || exit 1; \
 	  done  
 
 uninstall-links:
