cosmetic change in displaying error message when installing symlinks (use stderr instead of stdout, and exit 1 instead of false)
git-svn-id: svn://tug.org/texlive/trunk/Build/source@8198 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/texk/tex4htk/Makefile.in b/texk/tex4htk/Makefile.in
--- a/texk/tex4htk/Makefile.in
+++ b/texk/tex4htk/Makefile.in
@@ -40,8 +40,8 @@ install-exec: all
 	elif test -d "$(bindir)/../texmf-dist/scripts/tex4ht"; then \
 	  d=../texmf-dist/scripts/tex4ht; \
 	else \
-	  echo "Error: texmf-dist/scripts/tex4ht directory not found"; \
-	  false; \
+	  echo "Error: texmf-dist/scripts/tex4ht directory not found" >&2; \
+	  exit 1; \
 	fi; \
 	for p in $(shell_scripts); do rm -f $(bindir)/$$p; ln -s $$d/$$p.sh $(bindir)/$$p; done; \
 	for p in $(perl_scripts); do rm -f $(bindir)/$$p; ln -s $$d/$$p.pl $(bindir)/$$p; done
diff --git a/utils/xindy/user-commands/Makefile.am b/utils/xindy/user-commands/Makefile.am
--- a/utils/xindy/user-commands/Makefile.am
+++ b/utils/xindy/user-commands/Makefile.am
@@ -33,8 +33,8 @@ install-exec-hook: xindy
 	  ln -s ../texmf/scripts/xindy/xindy.pl $(bindir)/xindy; \
 	  ln -s ../texmf/scripts/xindy/texindy.pl $(bindir)/texindy; \
 	else \
-	  echo "Error: texmf/scripts/xindy directory not found"; \
-	  false; \
+	  echo "Error: texmf/scripts/xindy directory not found" >&2; \
+	  exit 1; \
 	fi
 else
     bin_SCRIPTS = xindy
