mention possibly missing ls-R when basic config files cannot be found (Bernhard Rosenkraenzer mail to tldistro, 2 Oct 2008 21:55:35)
git-svn-id: svn://tug.org/texlive/trunk/Build/source@16754 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/texk/tetex/fmtutil b/texk/tetex/fmtutil
--- a/texk/tetex/fmtutil
+++ b/texk/tetex/fmtutil
@@ -482,7 +482,7 @@ main()
   esac
 
   if test -n "$cfgparam"; then
-    test -f "$cnf_file" || abort "config file \`$cnf_file' not found"
+    test -f "$cnf_file" || abort "config file \`$cnf_file' not found (ls-R missing?)"
   fi
 
   if test -n "$cfgmaint"; then
