Metafont: Stricter checking in mftraptest
git-svn-id: svn://tug.org/texlive/trunk/Build/source@32726 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/texk/web2c/mftraptest b/texk/web2c/mftraptest
--- a/texk/web2c/mftraptest
+++ b/texk/web2c/mftraptest
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (C) 2009-2013 Peter Breitenlohner <tex-live@tug.org>
+# Copyright (C) 2009-2014 Peter Breitenlohner <tex-live@tug.org>
 # You may freely use, modify and/or distribute this file.
 
 testdir=$abs_srcdir/triptrap
@@ -11,10 +11,27 @@ rm -rf trapdir
 mkdir trapdir
 cd trapdir
 
-dvitype_args="-output-level=2 -dpi=72.27 -page-start='*.*.*.*.*.*.*.*.*.*'"
+mkdir a b
+cat >filter <<-\_EOF
+	s,^\*\*(trap\.mf,** \&trap  trap \
+	(trap.mf,
+	s/ (TeX Live 20[^)]*)//
+	s/base=trap [^)][^)]*)/base=trap)/
+	s/)  [0-9A-Z: ]*$/)/
+	s/usage [1-9][0-9&]* ([1-9][0-9&]* still/usage XX\&XX (YYY\&YYYYY still/
+	s/[1-9][0-9]* strings of total length [1-9][0-9]*/XXXX strings of total length YYYYY/
+	s/[1-9][0-9]* strings out of [1-9].*/XX strings out of YYY/
+	s/[1-9][0-9]* string characters out of [1-9].*/XXXX string characters out of YYYYY/
+	s/tokens out of [1-9][0-9]*/tokens out of YYYY/
+	s/out of [1-9][0-9]*i,[0-9nrpb,]*/out of YYi,YYYn,YYYr,YYYp,YYYb/
+	s/out of [1-9][0-9]*w,[0-9hdilkep,]*)/out of YYYw,YYh,YYd,YYi,YYYYl,YYYk,YYYe,YYp)/
+	s/METAFONT output 20..\...\...:..../METAFONT output 20YY.MM.DD:hhmm/
+	_EOF
 
 echo ">>> Running TRAP test for Metafont." >&2
 echo ">>> See $testdir/mftrap.diffs for example of acceptable diffs." >&2
+
+is_OK=:
 
 set -x
 
@@ -32,10 +49,21 @@ diff $testdir/mftrap.fot mftrap.fot
 diff $testdir/mftrap.log mftrap.log
 
 ../tftopl ./mftrap.tfm mftrap.pl || exit 1
-diff $testdir/mftrap.pl mftrap.pl
+diff $testdir/mftrap.pl mftrap.pl || is_OK=false
 
 ../gftype -m -i ./trap.72270gf >trap.typ || exit 1
 diff $testdir/trap.typ trap.typ
 
-exit 0
+for f in mftrapin.log mftrap.fot mftrap.log trap.typ; do
+  sed $testdir/$f -f filter >a/$f
+  sed $f -f filter >b/$f
+  diff a/$f b/$f || is_OK=false
+done
+
+$is_OK && {
+  echo ">>> All differences are acceptable." >&2
+} || {
+  echo ">>> There were some errors." >&2
+  exit 1
+}
 
