a little more info on acceptable diffs
git-svn-id: svn://tug.org/texlive/trunk/Build/source@33032 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/texk/web2c/mftraptest b/texk/web2c/mftraptest
--- a/texk/web2c/mftraptest
+++ b/texk/web2c/mftraptest
@@ -4,14 +4,16 @@
 # You may freely use, modify and/or distribute this file.
 
 testdir=$abs_srcdir/triptrap
-
 TEXMFCNF=$testdir; export TEXMFCNF
 
 rm -rf trapdir
 mkdir trapdir
 cd trapdir
-
 mkdir a b
+
+# See triptrap/README for explanation of why we believe these diffs are ok,
+# notably including the capsule numbers.
+
 cat >filter <<-\_EOF
 	s,^\*\*(trap\.mf,** \&trap  trap \
 	(trap.mf,
@@ -66,7 +68,6 @@ done
 $is_OK && {
   echo ">>> All differences are acceptable." >&2
 } || {
-  echo ">>> There were some errors." >&2
+  echo "*** Error(s) found in mf trap test, investigate!" >&2
   exit 1
 }
-
diff --git a/texk/web2c/triptest b/texk/web2c/triptest
--- a/texk/web2c/triptest
+++ b/texk/web2c/triptest
@@ -4,13 +4,15 @@
 # You may freely use, modify and/or distribute this file.
 
 testdir=$abs_srcdir/triptrap
-
 TEXMFCNF=$testdir; export TEXMFCNF
 
 rm -rf tripdir
 mkdir tripdir
 cd tripdir
 mkdir a b
+
+# See triptrap/README for explanation of why we believe these diffs are ok.
+
 cat >filter <<-\_EOF
 	s,^\*\*(\./trip\.tex ##,** \&trip  trip \
 	(trip.tex ##,
@@ -81,7 +83,6 @@ done
 $is_OK && {
   echo ">>> All differences are acceptable." >&2
 } || {
-  echo ">>> There were some errors." >&2
+  echo "*** Error(s) found in trip test, investigate!" >&2
   exit 1
 }
-
