towards TL2010: libs/
git-svn-id: svn://tug.org/texlive/trunk/Build/source@15957 c570f23f-e606-0410-a88d-b1316a301751

diff --git a/libs/Makefile.am b/libs/Makefile.am
--- a/libs/Makefile.am
+++ b/libs/Makefile.am
@@ -7,17 +7,14 @@
 ##
 ACLOCAL_AMFLAGS = -I ../m4 --force
 
-SUBDIRS = dummy . $(SUBLIBS)
-DIST_SUBDIRS = dummy $(DIST_SUBLIBS)
+SUBDIRS = . $(SUBLIBS)
+DIST_SUBDIRS = $(DIST_SUBLIBS)
 
 # just in case a subdirectory has added directories
 dist-hook:
 	rm -rf `find $(distdir) -name .svn`
 
-SUBLIBS_AUX = sublibsdir-configure sublibsdir-conf.args
-noinst_DATA = $(SUBLIBS_AUX)
-
-DISTCLEANFILES = $(noinst_DATA)
+CONFIG_AUX = ../subsubdir-conf.cmd
 
 all-local: sublibs
 
@@ -29,7 +26,7 @@ all-local: sublibs
 #
 # Sequentially configure and optionally build all libs subdirs;
 # code inspired by automake's way to handle recursive targets.
-sublibs: $(noinst_DATA)
+sublibs: $(CONFIG_AUX)
 	@failcom='exit 1'; \
 	for f in x $$MAKEFLAGS; do \
 	  case $$f in \
@@ -40,14 +37,16 @@ sublibs: $(noinst_DATA)
 	list='$(DIST_SUBLIBS)'; for sublibs in $$list; do \
 	  if test ! -f $$sublibs/Makefile; then \
 	    test -d $$sublibs || $(MKDIR_P) $$sublibs; \
-	    cmd=`cat $(SUBLIBS_AUX) | sed "s,SUBLIBSDIR,$$sublibs,g"`; \
+	    cmd=`cat $(CONFIG_AUX) | sed "s,auxdir/auxsub,libs/$$sublibs,g"`; \
 	    case " $(SUBLIBS) " in \
 	      *" $$sublibs "*) skip=;; \
 	      *) skip=' --disable-build';; \
 	    esac; \
 	    (cd $$sublibs && echo "=== configuring in $$sublibs (`pwd`)" && \
 	      echo "make: running $(SHELL) $$cmd$$skip" && \
-	      eval $(SHELL) $$cmd$$skip) && \
+	      CONFIG_SHELL=$(SHELL) && export CONFIG_SHELL && \
+	      eval $(SHELL) $$cmd$$skip || \
+	        { echo "=== configuring in $$sublibs failed"; exit 1; }) && \
 	    if test "x$$skip" = x; then \
 	      echo "Making all in $$sublibs" && \
 	      (cd $$sublibs && $(MAKE) $(AM_MAKEFLAGS) all); \
@@ -55,11 +54,7 @@ sublibs: $(noinst_DATA)
 	  fi; \
 	done; test -z "$$fail"
 
-sublibsdir-configure:
-	@echo "make in ./dummy failed to create the file $@"
-	exit 1
-
-sublibsdir-conf.args:
-	@echo "configure in ./dummy failed to create the file $@"
+../subsubdir-conf.cmd:
+	@echo "configure in ../auxdir/auxsub failed to create the file $@"
 	exit 1
 
diff --git a/libs/Makefile.in b/libs/Makefile.in
--- a/libs/Makefile.in
+++ b/libs/Makefile.in
@@ -14,7 +14,6 @@
 # PARTICULAR PURPOSE.
 
 @SET_MAKE@
-
 VPATH = @srcdir@
 pkgdatadir = $(datadir)/@PACKAGE@
 pkgincludedir = $(includedir)/@PACKAGE@
@@ -54,6 +53,7 @@ am__aclocal_m4_deps = $(top_srcdir)/../m4/kpse-common.m4 \
 	$(top_srcdir)/../m4/kpse-freetype2-flags.m4 \
 	$(top_srcdir)/../m4/kpse-gd-flags.m4 \
 	$(top_srcdir)/../m4/kpse-graphite-flags.m4 \
+	$(top_srcdir)/../m4/kpse-icu-flags.m4 \
 	$(top_srcdir)/../m4/kpse-kpathsea-flags.m4 \
 	$(top_srcdir)/../m4/kpse-libpng-flags.m4 \
 	$(top_srcdir)/../m4/kpse-options.m4 \
@@ -77,6 +77,7 @@ am__aclocal_m4_deps = $(top_srcdir)/../m4/kpse-common.m4 \
 	$(top_srcdir)/../texk/web2c/ac/web2c.ac \
 	$(top_srcdir)/../texk/afm2pl/ac/withenable.ac \
 	$(top_srcdir)/../texk/bibtex8/ac/withenable.ac \
+	$(top_srcdir)/../texk/bibtexu/ac/withenable.ac \
 	$(top_srcdir)/../texk/cjkutils/ac/withenable.ac \
 	$(top_srcdir)/../texk/detex/ac/withenable.ac \
 	$(top_srcdir)/../texk/devnag/ac/withenable.ac \
@@ -136,7 +137,6 @@ RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
 	install-pdf-recursive install-ps-recursive install-recursive \
 	installcheck-recursive installdirs-recursive pdf-recursive \
 	ps-recursive uninstall-recursive
-DATA = $(noinst_DATA)
 RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
   distclean-recursive maintainer-clean-recursive
 AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
@@ -176,7 +176,7 @@ am__relativize = \
     dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
   done; \
   reldir="$$dir2"
-DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
+DIST_ARCHIVES = $(distdir).tar.gz
 GZIP_ENV = --best
 distuninstallcheck_listfiles = find . -type f -print
 distcleancheck_listfiles = find . -type f -print
@@ -208,6 +208,7 @@ PACKAGE_BUGREPORT = @PACKAGE_BUGREPORT@
 PACKAGE_NAME = @PACKAGE_NAME@
 PACKAGE_STRING = @PACKAGE_STRING@
 PACKAGE_TARNAME = @PACKAGE_TARNAME@
+PACKAGE_URL = @PACKAGE_URL@
 PACKAGE_VERSION = @PACKAGE_VERSION@
 PATH_SEPARATOR = @PATH_SEPARATOR@
 SET_MAKE = @SET_MAKE@
@@ -264,11 +265,9 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 ACLOCAL_AMFLAGS = -I ../m4 --force
-SUBDIRS = dummy . $(SUBLIBS)
-DIST_SUBDIRS = dummy $(DIST_SUBLIBS)
-SUBLIBS_AUX = sublibsdir-configure sublibsdir-conf.args
-noinst_DATA = $(SUBLIBS_AUX)
-DISTCLEANFILES = $(noinst_DATA)
+SUBDIRS = . $(SUBLIBS)
+DIST_SUBDIRS = $(DIST_SUBLIBS)
+CONFIG_AUX = ../subsubdir-conf.cmd
 all: all-recursive
 
 .SUFFIXES:
@@ -514,6 +513,7 @@ distdir: $(DISTFILES)
 dist-gzip: distdir
 	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
 	$(am__remove_distdir)
+
 dist-bzip2: distdir
 	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
 	$(am__remove_distdir)
@@ -541,7 +541,6 @@ dist-zip: distdir
 
 dist dist-all: distdir
 	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
-	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
 	$(am__remove_distdir)
 
 # This target untars the dist file and tries a VPATH configuration.  Then
@@ -621,7 +620,7 @@ distcleancheck: distclean
 	       exit 1; } >&2
 check-am: all-am
 check: check-recursive
-all-am: Makefile $(DATA) all-local
+all-am: Makefile all-local
 installdirs: installdirs-recursive
 installdirs-am:
 install: install-recursive
@@ -645,7 +644,6 @@ clean-generic:
 distclean-generic:
 	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
 	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
-	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)
 
 maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
@@ -752,7 +750,7 @@ all-local: sublibs
 #
 # Sequentially configure and optionally build all libs subdirs;
 # code inspired by automake's way to handle recursive targets.
-sublibs: $(noinst_DATA)
+sublibs: $(CONFIG_AUX)
 	@failcom='exit 1'; \
 	for f in x $$MAKEFLAGS; do \
 	  case $$f in \
@@ -763,14 +761,16 @@ sublibs: $(noinst_DATA)
 	list='$(DIST_SUBLIBS)'; for sublibs in $$list; do \
 	  if test ! -f $$sublibs/Makefile; then \
 	    test -d $$sublibs || $(MKDIR_P) $$sublibs; \
-	    cmd=`cat $(SUBLIBS_AUX) | sed "s,SUBLIBSDIR,$$sublibs,g"`; \
+	    cmd=`cat $(CONFIG_AUX) | sed "s,auxdir/auxsub,libs/$$sublibs,g"`; \
 	    case " $(SUBLIBS) " in \
 	      *" $$sublibs "*) skip=;; \
 	      *) skip=' --disable-build';; \
 	    esac; \
 	    (cd $$sublibs && echo "=== configuring in $$sublibs (`pwd`)" && \
 	      echo "make: running $(SHELL) $$cmd$$skip" && \
-	      eval $(SHELL) $$cmd$$skip) && \
+	      CONFIG_SHELL=$(SHELL) && export CONFIG_SHELL && \
+	      eval $(SHELL) $$cmd$$skip || \
+	        { echo "=== configuring in $$sublibs failed"; exit 1; }) && \
 	    if test "x$$skip" = x; then \
 	      echo "Making all in $$sublibs" && \
 	      (cd $$sublibs && $(MAKE) $(AM_MAKEFLAGS) all); \
@@ -778,12 +778,8 @@ sublibs: $(noinst_DATA)
 	  fi; \
 	done; test -z "$$fail"
 
-sublibsdir-configure:
-	@echo "make in ./dummy failed to create the file $@"
-	exit 1
-
-sublibsdir-conf.args:
-	@echo "configure in ./dummy failed to create the file $@"
+../subsubdir-conf.cmd:
+	@echo "configure in ../auxdir/auxsub failed to create the file $@"
 	exit 1
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
